name: Go-Test-Build

on:
  push:
    branches: [ "*" ]
    paths:
      - cmd/**
      - internal/**
      - go.mod
  pull_request:
    branches: [ "*" ]
    paths:
      - cmd/**
      - internal/**
      - go.mod

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
